### ISSUE TITLE
Conekta on Firebase Functions

### ISSUE THREAD

**Issue by jesussangomez** [conekta/conekta-node#47]
I got this exception when I deploy on Firebase:

`TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/user_code/node_modules/conekta/lib/conekta.js:115:15)
    at self.callback (/user_code/node_modules/conekta/node_modules/request/request.js:368:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/user_code/node_modules/conekta/node_modules/request/request.js:1025:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)`

Any idea why  is this happening?

**Comment by jesussangomez** [comment]
Forget it, it was because of my firebase plan. It prevent external requests.

**Comment by cesmejia** [comment]
hey @jesussangomez where you able to succesfully integrate conekta with firebase functions for your payments? How did it go? Was it easy?
Looking forward to go full serverless! Thanks in advance man

**Comment by martinnv6** [comment]
Hey @jesussangomez I also want to know how did you implement firebase with conekta payments.
