### ISSUE TITLE
Couldn't capture pre_authorized order

### ISSUE THREAD

**Issue by pepeBarrera** [conekta/conekta-node#53]
According with the API: 
var order = Conekta.Order.find("ord_2fw8EWJusiRrxdPzT");
order.capture();

it throws an error on the server like: 
Note: When I check my account the order after run that node-code the status was paid):

C:\Users\dir\dir\dir\node_modules\conekta\
lib\conekta.js:380
        next(null, res)
        ^

TypeError: next is not a function
    at Object.next (C:\Users\dir\dir\dir\node_modules\conekta\lib\conekta.js:380:9)
    at Object.<anonymous> (C:\Users\dir\dir\dir\node_modules\conekta\lib\conekta.js:334:16)
    at Request._callback (C:\Users\dir\dir\dir\node_modules\conekta\lib\conekta.js:124:12)
    at Request.self.callback (C:\Users\dir\dir\dir\node_modules\request\request.js:368:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\dir\dir\dir\node_modules\request\request.js:1219:14)
    at emitOne (events.js:121:20)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\dir\dir\dir\node_modules\request\request.js:1167:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by JoValo** [comment]
Hola @pepeBarrera  gracias por notificarnos de este issue vamos a comenzar a hacer el debug del comportamiento que nos mencionas y lo atenderemos a la brevedad.

**Comment by GbalsaC** [comment]
@pepeBarrera Intenta acceder al objeto con Callback, probablemente la documentación está equivocada.
En el ejemplo de Refound se escribe diferente:

```javascript
conekta.Order.find("ord_2fw8EWJusiRrxdPzT", function(err, order) {
  // Observa como order se muestra en callback
  order.createRefund({
    "reason": "requested_by_client",
    "amount": 1000
  }, function(err, res) {
    console.log(res);
  });
});


```

**Comment by KarlaRobinson** [comment]
Thank you for noticing this! I am closing this issue because we have corrected the documentation of the capture method.
https://developers.conekta.com/api?language=node#capture-order
https://github.com/conekta/docs/pull/381/
