### ISSUE TITLE
Eliminar método de pago

### ISSUE THREAD

**Issue by cesargdm** [conekta/conekta-node#69]
Según la documentación para eliminar un método de pago el argumento a pasar sería el id del pago, pero esto ocasiona el siguiente error:

`TypeError: Cannot read property 'id' of undefined`
```
/[...]/node_modules/conekta/lib/conekta.js:866
    this._id = this._json.data[position].id
                                         ^

TypeError: Cannot read property 'id' of undefined
    at Object.get (/Users/cesargdm/sites/travel/node_modules/conekta/lib/conekta.js:866:42)
    at Object.conekta.Customer.find [as next] (/[...]/server/utils/conekta.js:57:32)
    at Object.<anonymous> (/Users/cesargdm/sites/travel/node_modules/conekta/lib/conekta.js:249:16)
    at Request._callback (/Users/cesargdm/sites/travel/node_modules/conekta/lib/conekta.js:126:12)
    at Request.self.callback (/[...]/node_modules/conekta/node_modules/request/request.js:368:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/[...]/node_modules/conekta/node_modules/request/request.js:1219:14)
    at emitOne (events.js:121:20)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/[...]/node_modules/conekta/node_modules/request/request.js:1167:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

Descubrí que en realidad hay que pasar el índice del método de pago a eliminar, lo cual no tiene sentido. Fix?

**Comment by fruizg0302** [comment]
Igual que el del payment source dejame revisar que onda. Gracias :D

**Comment by mauroarcet** [comment]
@cesargdm para entender un poco mejor, buscas eliminar un `payment_source` apartir de un `charge_id` o un `order_id`?

**Comment by cesargdm** [comment]
A partir del id del payment_source, justo como aparece en los docs
<img width="560" alt="screen shot 2018-10-22 at 8 53 11 pm" src="https://user-images.githubusercontent.com/10179494/47330058-860a3d80-d63c-11e8-95ca-0015de561e41.png">

**Comment by KarlaRobinson** [comment]
Thank you @cesargdm for noticing this.
To delete a ConektaCustomer payment_source you must indicate the payment_source **index**.
I am closing this issue as it has been corrected in the documentation:
https://developers.conekta.com/api#delete-payment-source
https://github.com/conekta/docs/pull/380
